// Auto-generated by http://json2ts.com

export interface Items {
  href: string;
}

export interface Links {
  items: Items;
}

export interface Entry {
  authority?: any;
  value: string;
  valueLang?: any;
  count: number;
  type: string;
  _links: Links;
}

export interface Embedded {
  entries: Entry[];
}

export interface Page {
  number: number;
  size: number;
  totalPages: number;
  totalElements: number;
}

export interface Next {
  href: string;
}

export interface Last {
  href: string;
}

export interface Self {
  href: string;
}

export interface RootLinks {
  next: Next;
  last: Last;
  self: Self;
}

export interface Authors {
  _embedded: Embedded;
  page: Page;
  _links: RootLinks;
}
